services:
  - type: web
    name: agnishield-backend
    env: python
    plan: free
    buildCommand: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      pip install --upgrade pip
    startCommand: "./venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000"
